name: semver-test
description: Tests the version outputs of semver-action
inputs:
  expected-version:
    description: The expected current version
    required: true
  actual-version:
    description: The actual current version
    required: true
  expected-next-version:
    description: The expected next version
    required: false
  actual-next-version:
    description: The actual next version
    required: false
  expected-next-snapshot-version:
    description: The expected next SNAPSHOT version
    required: false
  actual-next-snapshot-version:
    description: The actual next SNAPSHOT version
    required: false

runs:
  using: composite
  steps:
    - name: Compare Version
      run: |
        echo "Compare Version:"
        if [[ "${{ inputs.expected-version }}" != "${{ inputs.actual-version }}" ]]; then
          echo "::error::Expected: ${{ inputs.expected-version }}, Actual: ${{ inputs.actual-version }}"
          exit 1
        else
          echo "Expected: ${{ inputs.expected-version }}, Actual: ${{ inputs.actual-version }}"
        fi
      shell: bash
    - name: Compare Next Version
      run: |
        echo "Compare Next Version:"
        if [[ "${{ inputs.expected-build-version }}" != "${{ inputs.actual-next-version }}" ]]; then
          echo "::error::Expected: ${{ inputs.expected-next-version }}, Actual: ${{ inputs.actual-next-version }}"
          exit 1
        else
          echo "Expected: ${{ inputs.expected-next-version }}, Actual: ${{ inputs.actual-next-version }}"
        fi
      shell: bash
    - name: Compare Next SNAPSHOT Version
      run: |
        echo "Compare Next SNAPSHOT Version:"
        if [[ "${{ inputs.expected-next-snapshot-version }}" != "${{ inputs.actual-next-snapshot-version }}" ]]; then
          echo "::error::Expected: ${{ inputs.expected-next-snapshot-version }}, Actual: ${{ inputs.actual-next-snapshot-version }}"
          exit 1
        else
          echo "Expected: ${{ inputs.expected-next-snapshot-version }}, Actual: ${{ inputs.actual-next-snapshot-version.version }}"
        fi
      shell: bash
