name: Dispatch - Build and Release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: npm ci
      - run: npm run all
      - name: Verifying no unstaged changes
        run: __test__/verify-no-unstaged-changes.sh
      - run: npm run release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Get package.json version
        uses: ./
        id: get_version
        with:
          package-manager-type: npm
      - name: Push to Major version tag
        if: ${{ success() }}
        env:
          VERSION: ${{ steps.get_version.outputs.version }}
          MAJOR: ${{ steps.get_version.outputs.version-major }}
        run: |
          git config --local user.email "sysadmin@terradatum.com"
          git config --local user.name "Terradatum Automation"
          git remote set-url origin git@github.com:${GITHUB_REPOSITORY}.git
          git tag --force -a "v${MAJOR}" -m "Update to v${MAJOR} from ${VERSION}"
          git push --force --tags
