name: Dispatch - Build and Release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: true
          fetch-depth: 0
      - run: npm ci
      - run: npm run all
      - name: Verifying no unstaged changes
        run: __test__/verify-no-unstaged-changes.sh
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        id: semantic_release
        with:
          semantic_version: 16
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/git
            @semantic-release/exec
            conventional-changelog-conventionalcommits
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Get package.json version
        uses: ./
        id: get_version
        with:
          package-manager-type: npm
      - name: Push to Major version tag
        if: steps.semantic_release.outputs.new_release_published == 'true'
        env:
          VERSION: ${{ steps.get_version.outputs.version }}
          MAJOR: ${{ steps.get_version.outputs.major }}
        run: |
          git config --local user.email "sysadmin@terradatum.com"
          git config --local user.name "Terradatum Automation"
          git tag --force -a "v${MAJOR}" -m "Update to v${MAJOR} from ${VERSION}"
          git push --force --tags
